### ISSUE TITLE
[Java Template] RedshiftToGCS: empty validateInput method 

### ISSUE THREAD

**Issue by mattfsmith** [GoogleCloudPlatform/dataproc-templates#597] opened 2023-02-17 21:58 UTC
public void validateInput() {} } 

empty method.

Do we need to validate inputs (assumed yes). If we do, then let's fix this.

**Comment by saumyasinha-google** [comment] 2023-02-23 09:41
Duplicate of issue #603.
Hence, closing.

**Closed by saumyasinha-google** 2023-02-23 09:41 UTC
Labels: java, tech-debt
