### ISSUE TITLE
Publishing : Public post for Kafka to GCS Template

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#84] opened 2022-03-15 16:23 UTC

**Comment by shashank-google** [comment] 2022-05-10 17:11
@nikhil6790 Any updates ?

**Comment by nikhil6790** [comment] 2022-05-17 03:27
@shashank-google There is no update on this issue as of now. It is pending completion of   #60

**Comment by nikhil6790** [comment] 2023-01-24 19:58
Closing this issue as duplicate of  #396

**Closed by nikhil6790** 2023-01-24 19:58 UTC
Labels: good first issue, publishing, java, In Progress
